<a href="https://colab.research.google.com/github/Renan-Domingues/IntroductionToPytorch/blob/main/IntroductionPytorch_02_IntoductionTensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introduction to Pytorch Tensors
Tensors are the central data abstraction in PyTorch

In [ ]:
import torch
import math

In [ ]:
# The simplest way to create a tensor is with the torch.empty() call

x = torch.empty(3, 4)
print(type(x))
print(x)

<class 'torch.Tensor'>
tensor([[0.0000e+00, 0.0000e+00, 1.8077e-43, 0.0000e+00],
        [5.3858e-38, 4.4445e-41, 5.3858e-38, 4.4445e-41],
        [1.4013e-45,        nan, 1.4013e-45, 8.4078e-45]])


- this tensor is 2 dimensional,  having 3 rows and 4 columns.
- the return (torch.Tensor) is an alias for torch.FloatTensor.
- this random numbers is because torch.empty() call alocates memory for the tensor, but does not initialize in with any values (this number are memory at the time of allocation)


Brif note about tensors

- one dimensional tensor is called a vector
- 2 dimensional tensor is a matrix
- anything with more than 2 dimensional os kist called a tensor

In [ ]:
# let's create some tensors with values

zeros = torch.zeros(2, 3)
print(zeros)

ones = torch.ones(2, 3)
print(ones)

torch.manual_seed(42)
random = torch.rand(2, 3)
print(random)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])


### Random Tensors and Seeding


In [ ]:
# Now we are going to use manual_seed() to have the same random value

torch.manual_seed(1729)
random1 = torch.rand(2, 3)
print(random1)

random2 = torch.rand(2, 3)
print(random2)

torch.manual_seed(1729)
random3 = torch.rand(2, 3)
print(random3)

random4 = torch.rand(2, 3)
print(random4)


tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])
tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])
tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])
tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])


### Tensor shapes
when performing operations, often we need to have the same tensor shape - that means, having the same number of dimensions and the same number of cells in each dimension

for that, we have the ``torch.*_like()`` methods:

In [ ]:
x = torch.empty(2, 2, 3)
print(x.shape)
print(x)

empty_like_x = torch.empty_like(x)
print(empty_like_x.shape)
print(empty_like_x)

zeros_like_x = torch.zeros_like(x)
print(zeros_like_x.shape)
print(zeros_like_x)

ones_like_x = torch.ones_like(x)
print(ones_like_x.shape)
print(ones_like_x)

rand_like_x = torch.rand_like(x)
print(rand_like_x.shape)
print(rand_like_x)

torch.Size([2, 2, 3])
tensor([[[3.4648e+30, 3.3149e-41, 3.4657e+30],
         [3.3149e-41, 4.2160e-01, 6.9054e-02]],

        [[0.0000e+00, 0.0000e+00, 9.8091e-45],
         [8.4078e-45, 9.8091e-45, 1.4013e-44]]])
torch.Size([2, 2, 3])
tensor([[[ 5.3858e-38,  4.4445e-41,  3.4588e+30],
         [ 3.3149e-41,  4.4842e-44,  0.0000e+00]],

        [[ 1.5695e-43,  0.0000e+00, -3.1639e-07],
         [ 3.3156e-41,  0.0000e+00,  0.0000e+00]]])
torch.Size([2, 2, 3])
tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])
torch.Size([2, 2, 3])
tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]])
torch.Size([2, 2, 3])
tensor([[[0.6128, 0.1519, 0.0453],
         [0.5035, 0.9978, 0.3884]],

        [[0.6929, 0.1703, 0.1384],
         [0.4759, 0.7481, 0.0361]]])


the code ``.shape`` property. Shows the shape of a tensor,  in this case: [2, 2, 3] 1st=dimension, 2nd=rows, 3rd=columns.

using the ``.empty_like(), .zeros_like(), .ones_like(), .rand_like()`` it returns a tensor with identical dimensionality and extend

In [ ]:
# this way of creating a tensor will especify its data from PyTorch collection

some_constants = torch.tensor([[3.1415926, 2.71828], [1.61803, 0.0072897]])
print(some_constants)

some_integers = torch.tensor((2, 3, 5, 7, 11, 13, 17, 19))
print(some_integers)

more_integers = torch.tensor(((2, 4, 6), [3, 6, 9]))
print(more_integers)

tensor([[3.1416, 2.7183],
        [1.6180, 0.0073]])
tensor([ 2,  3,  5,  7, 11, 13, 17, 19])
tensor([[2, 4, 6],
        [3, 6, 9]])


Using torch.tensor() is the  most straightforward way to create a tensor if you already have data in a Pyton tuple or list

### Tensor Data Types

In [ ]:
a = torch.ones((2, 3), dtype=torch.int16)
print(a)

b = torch.rand((2, 3), dtype=torch.float64) * 20.
print(b)

c = b.to(torch.int32)
print(c)

tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)
tensor([[ 0.9956,  1.4148,  5.8364],
        [11.2406, 11.2083, 11.6692]], dtype=torch.float64)
tensor([[ 0,  1,  5],
        [11, 11, 11]], dtype=torch.int32)


### Math and Logic with Pytorch Tensors

In [ ]:
ones = torch.zeros(2, 2) + 1
twos = torch.ones(2, 2) * 2
threes = (torch.ones(2, 2) * 7 - 1) / 2
fours = twos ** 2
sqrt2s = twos ** 0.5

print(ones)
print(twos)
print(threes)
print(fours)
print(sqrt2s)

tensor([[1., 1.],
        [1., 1.]])
tensor([[2., 2.],
        [2., 2.]])
tensor([[3., 3.],
        [3., 3.]])
tensor([[4., 4.],
        [4., 4.]])
tensor([[1.4142, 1.4142],
        [1.4142, 1.4142]])


In [ ]:
powers2 = twos ** torch.tensor([[1, 2],  [3, 4]])
print(powers2)

fives = ones + fours
print(fives)

dozens = threes * fours
print(dozens)

tensor([[ 2.,  4.],
        [ 8., 16.]])
tensor([[5., 5.],
        [5., 5.]])
tensor([[12., 12.],
        [12., 12.]])


In [ ]:
# A intentional error (to show diferent dimensions)

a = torch.rand(2, 3)
b = torch.rand(3, 2)

print( a * b)

RuntimeError: ignored

In [ ]:
# The exception to same-shapes rule is tensor broadcasting

rand = torch.rand(2, 4)
doubled = rand * (torch.ones(1, 4) * 2)

print(rand)
print(doubled)

tensor([[0.2024, 0.5731, 0.7191, 0.4067],
        [0.7301, 0.6276, 0.7357, 0.0381]])
tensor([[0.4049, 1.1461, 1.4382, 0.8134],
        [1.4602, 1.2551, 1.4715, 0.0762]])


in this case they have similarities in their shapes.
in the exemple above, the (1, 4)tensor is multiplied by both rows of the (2, 4)tensor

this example of (2, 4) * (1, 4) returned a tensor of shape (2, 4)

The rules of broadcasting are
- Each tensor  must have at least one dimension - no empty tensors.
- Comparing the dimension sizes of the two tensors, going from last to first
    - Each dimension must be equal, or
    - One of the dimensions must be of size 1, or
    - The dimension does not exist in one of the tensors



In [ ]:
# Some examples of the rules that allow broadcasting

a = torch.ones(4, 3, 2)

b = a * torch.rand(3, 2) # 3rd and 2nd dims identical to a, dim 1 absent
print(b)

c = a * torch.rand(3, 1) # 3rd dim = 1, 2nd dim identical to a
print(c)

d = a * torch.rand(1, 2)  # 3rd dim identical to a, 2nd dim = 1
print(d)

tensor([[[0.2138, 0.5395],
         [0.3686, 0.4007],
         [0.7220, 0.8217]],

        [[0.2138, 0.5395],
         [0.3686, 0.4007],
         [0.7220, 0.8217]],

        [[0.2138, 0.5395],
         [0.3686, 0.4007],
         [0.7220, 0.8217]],

        [[0.2138, 0.5395],
         [0.3686, 0.4007],
         [0.7220, 0.8217]]])
tensor([[[0.2612, 0.2612],
         [0.7375, 0.7375],
         [0.8328, 0.8328]],

        [[0.2612, 0.2612],
         [0.7375, 0.7375],
         [0.8328, 0.8328]],

        [[0.2612, 0.2612],
         [0.7375, 0.7375],
         [0.8328, 0.8328]],

        [[0.2612, 0.2612],
         [0.7375, 0.7375],
         [0.8328, 0.8328]]])
tensor([[[0.8444, 0.2941],
         [0.8444, 0.2941],
         [0.8444, 0.2941]],

        [[0.8444, 0.2941],
         [0.8444, 0.2941],
         [0.8444, 0.2941]],

        [[0.8444, 0.2941],
         [0.8444, 0.2941],
         [0.8444, 0.2941]],

        [[0.8444, 0.2941],
         [0.8444, 0.2941],
         [0.8444, 0.2941]]])


In the example above

The multiplication operation that created (b) was broadcast over every “layer” of (a).

For (c), the operation was broadcast over ever layer and row of (a) - every 3-element column is identical.

For (d), we switched it around - now every row is identical, across layers and columns.


For more samples of Math operations
PyTorch has more the 300 operations type
check out the documentation: https://pytorch.org/docs/stable/torch.html#math-operations

Altering Tensors in Place

most binary operations on tensors will return a third, new tensor.
When we say c = a * b (where a and b are tensors), the new tensor c will occupy a region of memory distinct from the other tensors.

there will be times that I wish to alter a tensor in place, for example: if I'm doing a element-wise computation where I can discard intermediate values. For this, most of the math functions have a version with an appended underscore(_) that will alter a tensor in place.

In [ ]:
a = torch.tensor([0, math.pi / 4, math.pi / 2, 3 * math.pi / 4])
print('a:')
print(a)
print(torch.sin(a)) # this operation creates a new tensor in memory
print(a) # a has not changed

b = torch.tensor([0, math.pi / 4, math.pi / 2, 3 * math.pi / 4])
print('\nb:')
print(b)
print(torch.sin_(b)) # with underscore
print(b) # b has changed

a:
tensor([0.0000, 0.7854, 1.5708, 2.3562])
tensor([0.0000, 0.7071, 1.0000, 0.7071])
tensor([0.0000, 0.7854, 1.5708, 2.3562])

b:
tensor([0.0000, 0.7854, 1.5708, 2.3562])
tensor([0.0000, 0.7071, 1.0000, 0.7071])
tensor([0.0000, 0.7071, 1.0000, 0.7071])


In [ ]:
# for arithmetic  operations, there are functions that behave similarly:

a = torch.ones(2, 2)
b = torch.rand(2, 2)

print('Before:')
print(a)
print(b)
print('\nAfter adding:')
print(a.add_(b))
print(a)
print(b)
print('\nAfter multiplying:')
print(b.mul_(b))


Before:
tensor([[1., 1.],
        [1., 1.]])
tensor([[0.3788, 0.4567],
        [0.0649, 0.6677]])

After adding:
tensor([[1.3788, 1.4567],
        [1.0649, 1.6677]])
tensor([[1.3788, 1.4567],
        [1.0649, 1.6677]])
tensor([[0.3788, 0.4567],
        [0.0649, 0.6677]])

After multiplying:
tensor([[0.1435, 0.2086],
        [0.0042, 0.4459]])


these in- place arithmetic functionsyou  can see that the calling tensor is the one that gets changed in place

In [ ]:
# another option for placing the result of a computation in an existing, allocated tensor

a = torch.rand(2, 2)
b = torch.rand(2, 2)
c = torch.zeros(2, 2)
old_id = id(c)

print(c)

d = torch.matmul(a, b, out=c)
print(c) # content of c have changes

assert c is d # test c & d are same object, not just containing equal values
assert id(c) == old_id # make sure that our new c is the same object as the old one

torch.rand(2, 2, out=c) # works for creation too
print(c) # c has change again
assert id(c) == old_id

tensor([[0., 0.],
        [0., 0.]])
tensor([[0.3653, 0.8699],
        [0.2364, 0.3604]])
tensor([[0.0776, 0.4004],
        [0.9877, 0.0352]])


### Copying Tensors
As with any object in Python, assigning a tensor to a variable makes the variable a label of the tensor, and does not copy it. For example:

In [ ]:
a = torch.ones(2, 2)
b = a

a[0][1] = 516 # we change a...
print(b) # be is also altered

tensor([[  1., 516.],
        [  1.,   1.]])


If I want to separate copy of the data to work on, I should use the ``clone()`` method

In [ ]:
a = torch.ones(2, 2)
b = a.clone()

assert b is not a # different objects in memory
print(torch.eq(a, b)) #but still with the same contents

a[0][1] = 516 # a chenged
print(b) # b still ones

tensor([[True, True],
        [True, True]])
tensor([[1., 1.],
        [1., 1.]])


if I clone a variable, its autograd clone too
in this case I can use ``.detach()`` method on the souce tensor

In [ ]:
a = torch.rand(2, 2, requires_grad=True) # Turn on the autograd
print(a)

b = a.clone() # clone the autograd too
print(b)

c = a.detach().clone() # detach method detaches the tensor from its computation history
print(c) # c has no autograd due the detach

print(a) # a has not been altered, so it still has autograd

tensor([[0.0905, 0.4485],
        [0.8740, 0.2526]], requires_grad=True)
tensor([[0.0905, 0.4485],
        [0.8740, 0.2526]], grad_fn=<CloneBackward0>)
tensor([[0.0905, 0.4485],
        [0.8740, 0.2526]])
tensor([[0.0905, 0.4485],
        [0.8740, 0.2526]], requires_grad=True)


### Moving to GPU

In [ ]:
if torch.cuda.is_available():
  print('We have GPU!')
else:
  print('Sorry, CPU only')

We have GPU!


In [ ]:
# There are multiple ways to get your data onto your target device. You may do it at creation time:

if torch.cuda.is_available():
  gpu_rand = torch.rand(2, 2, device='cuda')
  print(gpu_rand)
else:
  print('sorry, CPU only')

tensor([[0.3344, 0.2640],
        [0.2119, 0.0582]], device='cuda:0')


By default, new tensors are created on the CPU

Lest's create a device handle that can be passed to my tensor instead of a string

In [ ]:
if torch.cuda.is_available():
  my_device = torch.device('cuda')
else:
  my_device = torch.device('cpu')
print(f'Device {my_device}')

x = torch.rand(2, 2, device=my_device)
print(x)

Device cuda
tensor([[0.0024, 0.6778],
        [0.2441, 0.6812]], device='cuda:0')


If I have a existing tensor living on one device, I can move to another using ``to()`` method

In [ ]:
y = torch.rand(2, 2)
y = y.to(my_device)

# Remember that the tensors should be in the same device for operations


### Manipulating Tensor Shapes

sometimes, you'll  need to change the shapes of your tensor

##### Changing the number of dimensions

In [ ]:
a = torch.rand(3, 226, 226)
b = a.unsqueeze(0)

print(a.shape)
print(b.shape) # if it was a image, now we have the batch dimension

torch.Size([3, 226, 226])
torch.Size([1, 3, 226, 226])


The unsqueeze() method adds a dimension of extent 1. unsqueeze(0) adds it as a new zeroth dimension - now you have a batch of one

In [ ]:
a = torch.rand(1, 20)
print(a.shape)
print(a)

b = a.squeeze(0)
print(b.shape)
print(b)

c = torch.rand(2, 2)
print(c.shape)

d = c.squeeze(0) # The squeeze don't afcted the shape because it only act on dimensions of extend 1
print(d.shape)

torch.Size([1, 20])
tensor([[0.2347, 0.1899, 0.4067, 0.1519, 0.1506, 0.9585, 0.7756, 0.8973, 0.4929,
         0.2367, 0.8194, 0.4509, 0.2690, 0.8381, 0.8207, 0.6818, 0.5057, 0.9335,
         0.9769, 0.2792]])
torch.Size([20])
tensor([0.2347, 0.1899, 0.4067, 0.1519, 0.1506, 0.9585, 0.7756, 0.8973, 0.4929,
        0.2367, 0.8194, 0.4509, 0.2690, 0.8381, 0.8207, 0.6818, 0.5057, 0.9335,
        0.9769, 0.2792])
torch.Size([2, 2])
torch.Size([2, 2])


What if the random vector had just been 3-element vector? We'd lose the ability to do the broadcast, because the final dimensions would not match up according to the broadcasting rules. unsqueeze() comes to the rescue:

In [ ]:
a = torch.ones(4, 3, 2)
b = torch. rand(3) # trying to multiply a * b will give a runtime error
c = b.unsqueeze(1) # The number 1 is the place of the new dimension
print(c.shape)
print(a * c)

torch.Size([3, 1])
tensor([[[0.8625, 0.8625],
         [0.6191, 0.6191],
         [0.9935, 0.9935]],

        [[0.8625, 0.8625],
         [0.6191, 0.6191],
         [0.9935, 0.9935]],

        [[0.8625, 0.8625],
         [0.6191, 0.6191],
         [0.9935, 0.9935]],

        [[0.8625, 0.8625],
         [0.6191, 0.6191],
         [0.9935, 0.9935]]])


In [ ]:
# unsqueeze and squeeze in-place version

batch_me = torch.rand(3, 226, 226)
print(batch_me.shape)
batch_me.unsqueeze_(0)
print(batch_me.shape)

torch.Size([3, 226, 226])
torch.Size([1, 3, 226, 226])


In [ ]:
# redmensioning a tensor (image to 1 dimensional)

output3d = torch.rand(6, 20, 20)
print(output3d.shape)

input1d = output3d.reshape(6 * 20 * 20)
print(input1d.shape)

# can also call it as a method on the torch module:
print(torch.reshape(output3d, (6 * 20 * 20,)).shape)

torch.Size([6, 20, 20])
torch.Size([2400])
torch.Size([2400])


### Numpy Bridge

Switching between ndarrays and PyTorch tensors:

In [ ]:
import numpy as np

numpy_array = np.ones((2, 3))
print(numpy_array)

pytorch_tensor = torch.from_numpy(numpy_array)
print(pytorch_tensor)

[[1. 1. 1.]
 [1. 1. 1.]]
tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


Pytorch creates a tensor of the same shape and data as numpy
float64 is the numpy default

In [ ]:
pytorch_rand = torch.rand(2, 3)
print(pytorch_rand)

numpy_rand = pytorch_rand.numpy()
print(numpy_rand)
print(numpy_rand.dtype)

tensor([[0.3465, 0.1790, 0.8715],
        [0.5255, 0.1814, 0.2284]])
[[0.34647584 0.17902076 0.87154263]
 [0.52549195 0.18138081 0.22844744]]
float32


In [ ]:
# Theses converted objects are using the same inderlying memory as their souce objects
# meaning that changes to one are reflected in the other:

numpy_array[1, 1] = 23
print(pytorch_tensor)

pytorch_rand[1, 1] = 17
print(numpy_rand)

tensor([[ 1.,  1.,  1.],
        [ 1., 23.,  1.]], dtype=torch.float64)
[[ 0.34647584  0.17902076  0.87154263]
 [ 0.52549195 17.          0.22844744]]
